import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import Navbar from '@/components/navbar/Navbar';
import '@/styles/_gloabl.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
          <Navbar />
        <main className='main'>

        
          {children}
        </main>
          <Footer/>
      </body>
    </html>
  );
}
