import ContextProvidor from '@/components/children/layout';
import '@/styles/_gloabl.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

   
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
         <ContextProvidor children={children}/>
      </body>
    </html>
  );
}
